version: "3"

services:
  flask:
    image: python
    container_name: flask
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_db:/usr/local/mongodb/
